"""
PYTHON SCRIPT FOR GUI APPLICATION FOR ROV. CONTAINS AUTOGENERATED 
GUI OBJECTS FROM QT DESIGNER AND FUNCTIONS NEEDED FOR GUI AND 
COMMUNICATION THE WORK TOGETHER.
"""
from PyQt5 import QtGui
from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QWidget, QApplication, QLabel, QVBoxLayout
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import pyqtSignal, pyqtSlot, Qt, QThread,QTime,QTimer
import cv2
import numpy as np
import config

class VideoThread(QThread):
    change_pixmap_signal = pyqtSignal(np.ndarray)

    def __init__(self):
        super().__init__()
        self._run_flag = True

    def run(self):
        while self._run_flag:
            try:
                if (len(config.rovCamera) > 10):
                    self.change_pixmap_signal.emit(config.rovCamera)
                    config.rovCamera = np.array([])
            except:
                continue

    def stop(self):
        self._run_flag = False
        self.wait()

class App(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("ROV-AIP USER INTERFACE")
        self.setGeometry(0,0,2560,1440)
        self.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.g = 9.81 # [m/s^2]
        self.density = 1000 # [kg/m^3]
        self.prevLockedZones = [True] * 8

        self.image_label = QLabel(self)
        self.image_label.setGeometry(690, 0, 1221, 671) 
        self.image_label.setFrameShape(QtWidgets.QFrame.Panel)

        self.sonar=QLabel(self)
        self.sonar.setText("Sonar_Placeholder")
        self.sonar.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.sonar.setGeometry(15, 15, 640, 640)
        self.sonar.setFrameShape(QtWidgets.QFrame.Panel)

        self.Forward = QtWidgets.QToolButton(self)
        self.Forward.setGeometry(QtCore.QRect(1280, 770, 51, 41))
        self.Forward.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Forward.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_forward.png'))
        self.Forward.setIconSize(QtCore.QSize(32, 32))
        self.Forward.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Forward.setArrowType(QtCore.Qt.NoArrow)
        self.Forward.setObjectName("Forward")
        self.Forward.pressed.connect(lambda: self.activateZone(0))
        self.Forward.released.connect(self.release)

        self.Reverse = QtWidgets.QToolButton(self)
        self.Reverse.setGeometry(QtCore.QRect(1280, 870, 51, 41))
        self.Reverse.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Reverse.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_reverse.png'))
        self.Reverse.setIconSize(QtCore.QSize(32, 32))
        self.Reverse.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Reverse.setArrowType(QtCore.Qt.NoArrow)
        self.Reverse.setObjectName("Reverse")
        self.Reverse.pressed.connect(lambda: self.activateZone(4))
        self.Reverse.released.connect(self.release)

        self.Left = QtWidgets.QToolButton(self)
        self.Left.setGeometry(QtCore.QRect(1210, 820, 51, 41))
        self.Left.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Left.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_left.png'))
        self.Left.setIconSize(QtCore.QSize(32, 32))
        self.Left.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Left.setArrowType(QtCore.Qt.NoArrow)
        self.Left.setObjectName("Left")
        self.Left.pressed.connect(lambda: self.activateZone(6))
        self.Left.released.connect(self.release)

        self.Right = QtWidgets.QToolButton(self)
        self.Right.setGeometry(QtCore.QRect(1350, 820, 51, 41))
        self.Right.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Right.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_right.png'))
        self.Right.setIconSize(QtCore.QSize(32, 32))
        self.Right.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Right.setArrowType(QtCore.Qt.NoArrow)
        self.Right.setObjectName("Right")
        self.Right.pressed.connect(lambda: self.activateZone(2))
        self.Right.released.connect(self.release)

        self.ForwardRight = QtWidgets.QToolButton(self)
        self.ForwardRight.setGeometry(QtCore.QRect(1350, 770, 51, 41))
        self.ForwardRight.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ForwardRight.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_forward_right.png'))
        self.ForwardRight.setIconSize(QtCore.QSize(32, 32))
        self.ForwardRight.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.ForwardRight.setObjectName("ForwardRight")
        self.ForwardRight.pressed.connect(lambda: self.activateZone(1))
        self.ForwardRight.released.connect(self.release)

        self.ForwardLeft = QtWidgets.QToolButton(self)
        self.ForwardLeft.setGeometry(QtCore.QRect(1210, 770, 51, 41))
        self.ForwardLeft.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ForwardLeft.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_forward_left.png'))
        self.ForwardLeft.setIconSize(QtCore.QSize(32, 32))
        self.ForwardLeft.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.ForwardLeft.setObjectName("ForwardLeft")
        self.ForwardLeft.pressed.connect(lambda: self.activateZone(7))
        self.ForwardLeft.released.connect(self.release)

        self.ReverseLeft = QtWidgets.QToolButton(self)
        self.ReverseLeft.setGeometry(QtCore.QRect(1210, 870, 51, 41))
        self.ReverseLeft.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ReverseLeft.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_reverse_left.png'))
        self.ReverseLeft.setIconSize(QtCore.QSize(32, 32))
        self.ReverseLeft.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.ReverseLeft.setObjectName("ReverseLeft")
        self.ReverseLeft.pressed.connect(lambda: self.activateZone(5))
        self.ReverseLeft.released.connect(self.release)

        self.ReverseRight = QtWidgets.QToolButton(self)
        self.ReverseRight.setGeometry(QtCore.QRect(1350, 870, 51, 41))
        self.ReverseRight.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ReverseRight.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_reverse_right.png'))
        self.ReverseRight.setIconSize(QtCore.QSize(32, 32))
        self.ReverseRight.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.ReverseRight.setObjectName("ReverseRight")
        self.ReverseRight.pressed.connect(lambda: self.activateZone(3))
        self.ReverseRight.released.connect(self.release)

        self.CounterClockwise = QtWidgets.QToolButton(self)
        self.CounterClockwise.setGeometry(QtCore.QRect(1210, 710, 51, 41))
        self.CounterClockwise.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.CounterClockwise.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_rotate_left.png'))
        self.CounterClockwise.setIconSize(QtCore.QSize(32, 32))
        self.CounterClockwise.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.CounterClockwise.setObjectName("CounterClockwise")
        self.CounterClockwise.pressed.connect(lambda: self.activateZone(8))
        self.CounterClockwise.released.connect(self.release)

        self.Clockwise = QtWidgets.QToolButton(self)
        self.Clockwise.setGeometry(QtCore.QRect(1350, 710, 51, 41))
        self.Clockwise.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Clockwise.setIcon(QtGui.QIcon('GUI_interface\Icons\icon_rotate_right.png'))
        self.Clockwise.setIconSize(QtCore.QSize(32, 32))
        self.Clockwise.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Clockwise.setObjectName("Clockwise")
        self.Clockwise.pressed.connect(lambda: self.activateZone(9))
        self.Clockwise.released.connect(self.release)

        self.Temp = QtWidgets.QLCDNumber(self)
        self.Temp.setGeometry(QtCore.QRect(30, 710, 141, 31))
        self.Temp.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Temp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Temp.setSmallDecimalPoint(True)
        self.Temp.setDigitCount(8)
        self.Temp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Temp.setProperty("value", 0.0)
        self.Temp.setObjectName("Temp")
        self.Temp.display(999)

        self.Depth = QtWidgets.QLCDNumber(self)
        self.Depth.setGeometry(QtCore.QRect(30, 790, 141, 31))
        self.Depth.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Depth.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Depth.setSmallDecimalPoint(True)
        self.Depth.setDigitCount(8)
        self.Depth.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Depth.setObjectName("Depth")
        self.Depth.display(999)

        self.Salinity = QtWidgets.QLCDNumber(self)
        self.Salinity.setGeometry(QtCore.QRect(30, 870, 141, 31))
        self.Salinity.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Salinity.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Salinity.setSmallDecimalPoint(True)
        self.Salinity.setDigitCount(8)
        self.Salinity.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Salinity.setObjectName("Salinity")
        self.Salinity.display(999)

        self.Conductivity = QtWidgets.QLCDNumber(self)
        self.Conductivity.setGeometry(QtCore.QRect(30, 950, 141, 31))
        self.Conductivity.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Conductivity.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Conductivity.setSmallDecimalPoint(True)
        self.Conductivity.setDigitCount(8)
        self.Conductivity.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Conductivity.setObjectName("Conductivity")
        self.Conductivity.display(999)

        self.Density = QtWidgets.QLCDNumber(self)
        self.Density.setGeometry(QtCore.QRect(30, 1030, 141, 31))
        self.Density.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Density.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Density.setSmallDecimalPoint(True)
        self.Density.setDigitCount(8)
        self.Density.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Density.setObjectName("Density")
        self.Density.display(999)

        self.Light_Value_Slider = QtWidgets.QSlider(self)
        self.Light_Value_Slider.setGeometry(QtCore.QRect(920, 710, 61, 201))
        self.Light_Value_Slider.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Light_Value_Slider.setOrientation(QtCore.Qt.Vertical)
        self.Light_Value_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Light_Value_Slider.setObjectName("Light_Value_Slider")
        self.Light_Value_Slider.setMaximum(255)
        self.Light_Value_Slider.setMinimum(0)
        self.Light_Value_Slider.valueChanged.connect(self.userInteractLights)

        self.ResetButton = QtWidgets.QPushButton(self)
        self.ResetButton.setGeometry(QtCore.QRect(1080, 710, 100, 100))
        self.ResetButton.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ResetButton.setObjectName("ResetButton")
        self.ResetButton.setText("Reset\ninterlocked\nzones")
        self.ResetButton.pressed.connect(self.setReset)
        self.ResetButton.released.connect(self.releaseReset)

        self.TakePhoto = QtWidgets.QPushButton(self)
        self.TakePhoto.setGeometry(QtCore.QRect(1740, 710, 171, 61))
        self.TakePhoto.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.TakePhoto.setObjectName("TakePhoto")
        self.TakePhoto.setText("Take HD photo")
        self.TakePhoto.pressed.connect(self.takePhoto)
        self.TakePhoto.released.connect(self.streamVideo)

        self.StartVideo = QtWidgets.QPushButton("toggle", self)
        self.StartVideo.setGeometry(QtCore.QRect(1740, 810, 171, 61))
        self.StartVideo.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.StartVideo.setObjectName("StartVideo")
        self.StartVideo.setText("Start video capture")
        self.StartVideo.setCheckable(True)
        self.StartVideo.clicked.connect(self.takeVideo)

        self.ScanMode20m = QtWidgets.QPushButton(self)
        self.ScanMode20m.setGeometry(QtCore.QRect(450, 710, 200, 71))
        self.ScanMode20m.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ScanMode20m.setObjectName("ScanMode20m")
        self.ScanMode20m.setText("Scanning [20m]")
        self.ScanMode20m.clicked.connect(lambda: self.userInteractModeSonar(0))

        self.ScanMode50m = QtWidgets.QPushButton(self)
        self.ScanMode50m.setGeometry(QtCore.QRect(450, 790, 200, 71))
        self.ScanMode50m.setStyleSheet("background-color: rgb(50, 205, 50);")
        self.ScanMode50m.setObjectName("ScanMode50m")
        self.ScanMode50m.setText("Scanning [50m]")
        self.ScanMode50m.clicked.connect(lambda: self.userInteractModeSonar(1))
        
        self.CollisionAvoid2m = QtWidgets.QPushButton(self)
        self.CollisionAvoid2m.setGeometry(QtCore.QRect(450, 870, 200, 71))
        self.CollisionAvoid2m.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.CollisionAvoid2m.setObjectName("CollisionAvoid2m")
        self.CollisionAvoid2m.setText("Collision Prevention [2m]")
        self.CollisionAvoid2m.clicked.connect(lambda: self.userInteractModeSonar(2))

        self.CollisionAvoid4m = QtWidgets.QPushButton(self)
        self.CollisionAvoid4m.setGeometry(QtCore.QRect(450, 950, 200, 71))
        self.CollisionAvoid4m.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.CollisionAvoid4m.setObjectName("CollisionAvoid4m")
        self.CollisionAvoid4m.setText("Collision Prevention [4m]")
        self.CollisionAvoid4m.clicked.connect(lambda: self.userInteractModeSonar(3))

        self.lblTemperature = QtWidgets.QLabel(self)
        self.lblTemperature.setGeometry(QtCore.QRect(30, 680, 141, 21))
        self.lblTemperature.setStyleSheet("\n""background-color: rgb(134, 134, 134);")
        self.lblTemperature.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblTemperature.setObjectName("lblTemperature")
        self.lblTemperature.setText("Temperature [°C]:")

        self.lblDepth = QtWidgets.QLabel(self)
        self.lblDepth.setGeometry(QtCore.QRect(30, 760, 141, 21))
        self.lblDepth.setStyleSheet("\n""background-color: rgb(134, 134, 134);")
        self.lblDepth.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblDepth.setObjectName("lblDepth")
        self.lblDepth.setText("Depth [m]:")

        self.lblSalinity = QtWidgets.QLabel(self)
        self.lblSalinity.setGeometry(QtCore.QRect(30, 840, 141, 21))
        self.lblSalinity.setStyleSheet("\n""background-color: rgb(134, 134, 134);")
        self.lblSalinity.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblSalinity.setObjectName("lblSalinity")
        self.lblSalinity.setText("Salinity [g/kg] PSU:")

        self.lblConductivity = QtWidgets.QLabel(self)
        self.lblConductivity.setGeometry(QtCore.QRect(30, 920, 141, 21))
        self.lblConductivity.setStyleSheet("\n""background-color: rgb(134, 134, 134);")
        self.lblConductivity.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblConductivity.setObjectName("lblConductivity")
        self.lblConductivity.setText("Conductivity [mS/cm]:")

        self.lblDensity = QtWidgets.QLabel(self)
        self.lblDensity.setGeometry(QtCore.QRect(30, 1000, 141, 21))
        self.lblDensity.setStyleSheet("\n""background-color: rgb(134, 134, 134);")
        self.lblDensity.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblDensity.setObjectName("lblDensity")
        self.lblDensity.setText("Water density [kg/m^3]:")

        self.lblLightIntensity = QtWidgets.QLabel(self)
        self.lblLightIntensity.setGeometry(QtCore.QRect(900, 680, 101, 21))
        self.lblLightIntensity.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.lblLightIntensity.setFrameShape(QtWidgets.QFrame.Box)
        self.lblLightIntensity.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblLightIntensity.setObjectName("lblLightIntensity")
        self.lblLightIntensity.setText("Light intensity")

        self.lblControls = QtWidgets.QLabel(self)
        self.lblControls.setGeometry(QtCore.QRect(1255, 675, 100, 30))
        self.lblControls.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.lblControls.setFrameShape(QtWidgets.QFrame.Box)
        self.lblControls.setObjectName("lblControls")
        self.lblControls.setFont(QFont('Arial', 14))
        self.lblControls.setText("Controls")

        self.lblAlarms = QtWidgets.QLabel(self)
        self.lblAlarms.setGeometry(QtCore.QRect(1500, 675, 100, 30))
        self.lblAlarms.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.lblAlarms.setFrameShape(QtWidgets.QFrame.Box)
        self.lblAlarms.setObjectName("lblAlarms")
        self.lblAlarms.setFont(QFont('Arial', 14))
        self.lblAlarms.setText("Alarms")

        self.lblLeaks = QtWidgets.QLabel(self)
        self.lblLeaks.setGeometry(QtCore.QRect(1500, 730, 100, 60))
        self.lblLeaks.setStyleSheet("background-color: rgb(60, 179, 113);")
        self.lblLeaks.setObjectName("lblLeaks")
        self.lblLeaks.setText("   No detected\n       leaks")

        self.SonarMode = QtWidgets.QLabel(self)
        self.SonarMode.setGeometry(QtCore.QRect(440, 680, 211, 21))
        self.SonarMode.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.SonarMode.setFrameShape(QtWidgets.QFrame.Box)
        self.SonarMode.setObjectName("SonarMode")
        self.SonarMode.setText("Current Sonar Mode: ")
        

        # Create new thread that handles video stream
        self.thread = VideoThread()
        # Connect thread to function that updates image
        self.thread.change_pixmap_signal.connect(self.update_image)
        # Start thread
        self.thread.start()


    def closeEvent(self, event):
        self.thread.stop()
        event.accept()

    def update_image(self, cv_img):
        qt_img = self.convert_video_qt(cv_img)
        self.image_label.setPixmap(qt_img)
    
    def update_sonar(self, cv_img):
        qt_img = self.convert_sonar_qt(cv_img)
        self.sonar.setPixmap(qt_img)
    
    def convert_video_qt(self, cv_img):
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(1920,960, Qt.KeepAspectRatio)
        return QPixmap.fromImage(p)

    def convert_sonar_qt(self, cv_img):
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        return QPixmap.fromImage(convert_to_Qt_format)

    def setDisplayValues(self, temp, depth, leak, lockedZones,
    salinity, conductivity, density):
        self.Temp.display(temp)
        self.Depth.display(depth)
        self.Salinity.display(salinity)
        self.Conductivity.display(conductivity)
        self.displayLeakStatus(leak)
        self.density = density
        self.Density.display(self.density)
        self.configureZonesDisplay(lockedZones)

    def displayLeakStatus(self, leak):
        if leak:
            self.lblLeaks.setStyleSheet("background-color: rgb(255, 0, 0);")
            self.lblLeaks.setText("    DETECTED\n       LEAKS")
    
    def configureZonesDisplay(self, lockedZones):
        if lockedZones == self.prevLockedZones:
            return
        else:
            print("Changes in locked zones array discovered")
            for idx, zoneState in enumerate(lockedZones):
                if lockedZones[idx] != self.prevLockedZones[idx]:
                    if zoneState:
                        self.setLockedStatus(idx)
                    else:
                        self.resetLockedStatus(idx)
                    break
            self.prevLockedZones = lockedZones
    
    def setLockedStatus(self, zone):
        if zone == 0:
            self.Forward.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 1:
            self.ForwardRight.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 2:
            self.Right.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 3:
            self.ReverseRight.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 4:
            self.Reverse.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 5:
            self.ReverseLeft.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 6:
            self.Left.setStyleSheet("background-color: rgb(200, 134, 134);")
        elif zone == 7:
            self.ForwardLeft.setStyleSheet("background-color: rgb(200, 134, 134);")

    def resetLockedStatus(self, zone):
        if zone == 0:
            self.Forward.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 1:
            self.ForwardRight.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 2:
            self.Right.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 3:
            self.ReverseRight.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 4:
            self.Reverse.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 5:
            self.ReverseLeft.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 6:
            self.Left.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif zone == 7:
            self.ForwardLeft.setStyleSheet("background-color: rgb(134, 134, 134);")

    def resetAllLockedStatus(self):
        self.prevLockedZones = [False] * 8
        self.Forward.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ForwardRight.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Right.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ReverseRight.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Reverse.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ReverseLeft.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.Left.setStyleSheet("background-color: rgb(134, 134, 134);")
        self.ForwardLeft.setStyleSheet("background-color: rgb(134, 134, 134);")

    def release(self):
        config.runZone = -1
        config.newCommands = True

    def activateZone(self, zone):
        config.runZone = zone
        config.newCommands = True

    def userInteractModeSonar(self, mode):
        display_string = ""
        if mode == 0:
            display_string = "Scanning [20m]"
            self.ScanMode50m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.ScanMode20m.setStyleSheet("background-color: rgb(50, 205, 50);")
            self.CollisionAvoid2m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.CollisionAvoid4m.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif mode == 1:
            display_string = "Scanning [50m]"
            self.ScanMode50m.setStyleSheet("background-color: rgb(50, 205, 50);")
            self.ScanMode20m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.CollisionAvoid2m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.CollisionAvoid4m.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif mode == 2:
            display_string = "Collision [2m]"
            self.ScanMode50m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.ScanMode20m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.CollisionAvoid2m.setStyleSheet("background-color: rgb(50, 205, 50);")
            self.CollisionAvoid4m.setStyleSheet("background-color: rgb(134, 134, 134);")
        elif mode == 3:
            display_string = "Collision [4m]"
            self.ScanMode50m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.ScanMode20m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.CollisionAvoid2m.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.CollisionAvoid4m.setStyleSheet("background-color: rgb(50, 205, 50);")

        self.SonarMode.setText(f"Sonar Mode: {display_string}")
        config.mode = mode
        config.newCommands = True

    def userInteractSpeeds(self):
        config.motorSpeed = self.Motor_Speed_Slider.value()
        config.newCommands = True
    
    def userInteractLights(self):
        config.light = self.Light_Value_Slider.value()
        config.newCommands = True

    def setReset(self):
        self.resetAllLockedStatus()
        config.forceReset = True
        config.newCommands = True

    def releaseReset(self):
        config.forceReset = False
        config.newCommands = True

    def takePhoto(self):
        self.TakePhoto.setStyleSheet("background-color: rgb(50, 205, 50);")
        config.takePhoto = True
        config.newCommands = True

    def takeVideo(self):
        if config.takeVideo == False:
            self.StartVideo.setStyleSheet("background-color: rgb(50, 205, 50);")
            self.StartVideo.setText("Capturing video...")
            config.takeVideo = True
        else:
            self.StartVideo.setStyleSheet("background-color: rgb(134, 134, 134);")
            self.StartVideo.setText("Start video capture")
            config.takeVideo = False

        config.newCommands = True

    def streamVideo(self):
        self.TakePhoto.setStyleSheet("background-color: rgb(134, 134, 134);")
        config.takePhoto = False
        config.newCommands = True


















